[settings]
minimum_release_age_excludes = [
    "github:can1357/oh-my-pi"
]

[tools]
# ====================
# Core Languages & Runtimes
# ====================
bun = "latest"
go = "latest"
node = "lts"
python = "latest"
rust = "latest"
uv = "latest"

# ====================
# Language Servers & Dev Tools
# ====================
"github:phpactor/phpactor" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
# "github:jorgsowa/php-lsp" = "latest"

# ====================
# AI & Custom Agents
# ====================
"github:can1357/oh-my-pi" = "latest"
"npm:skills" = "latest"
