git:
  pagers:
    - colorArg: always
      pager: 'delta --dark --paging=never --features=dracula --line-numbers --hyperlinks --hyperlinks-file-link-format="idea://open?file={path}&line={line}"'

gui:
  theme:
    activeBorderColor:
      - "#FF79C6"
      - bold
    inactiveBorderColor:
      - "#BD93F9"
    searchingActiveBorderColor:
      - "#8BE9FD"
      - bold
    optionsTextColor:
      - "#6272A4"
    selectedLineBgColor:
      - "#6272A4"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#6272A4"
    cherryPickedCommitBgColor:
      - "#8BE9FD"
    markedBaseCommitFgColor:
      - "#8BE9FD"
    markedBaseCommitBgColor:
      - "#F1FA8C"
    unstagedChangesColor:
      - "#FF5555"
    defaultFgColor:
      - "#F8F8F2"

keybinding:
  universal:
    prevItem-alt: 'l' # Up (Shifted from k)
    nextItem-alt: 'k' # Down (Shifted from j)
    prevBlock-alt: 'j' # Left / Previous Panel (Shifted from h)
    nextBlock-alt: ';' # Right / Next Panel (Shifted from l)
    scrollUpMain-alt1: 'L' # Scroll main panel up (Shifted from K)
    scrollDownMain-alt1: 'K' # Scroll main panel down (Shifted from J)

os:
  editPreset: 'nvim'
